 

site_name: QR Comer
site_description: Repositório da disciplina de QR Comer
repo_url: https://github.com/fga-desenho-2019-2/Wiki
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/fga-desenho-2019-2/Wiki/">QR Comer</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: assets/img/logo.png
  favicon: favicon.ico
  palette:
    primary: 'white'

    
extra:
  social:
    - type: 'github'
      link: 'https://github.com/fga-desenho-2019-2/Wiki'

plugins:
  - search

extra_css:
  - assets/css/landing-page.css
  - assets/css/extra.css

extra_javascript:
  - assets/js/jquery.min.js  
  - assets/js/jquery.zoom.min.js  
  - assets/js/extra.js  



lang:
  - 'pt'

pages:
  - Home: 'index.html'
  - Dinâmica e Seminário I:
      - Termo de abertura de projeto: 'seminario1/tap.md'
      - Design Sprint: 'seminario1/design_sprint.md'
  - Dinâmica e Seminário II:
      - Metodologia: 'seminario2/metodologia.md'
      - Metodologia - Elicitação de Requisitos: 'seminario2/metodologia-elicitacao.md'
      - Padronizações e Processos: 'seminario2/padroes_processos.md'
      - Diagramas: 'seminario2/diagramas.md'
      - Arquitetura: 'seminario2/arquitetura.md'
  - Dinâmica e Seminário III:
      - Diagramas estáticos: 'seminario3/diagramas_estaticos.md'
      - Diagramas dinâmicos: 'seminario3/diagramas_dinamicos.md'
  - Dinâmica e Seminário IV:
      - GoF's: 
        - Criacionais: 'seminario4/criacionais.md'
        - Estruturais: 'seminario4/estruturais.md'
        - Comportamentais: 'seminario4/comportamentais.md'
      - Emergentes & Consumidos: 'seminario4/emergentes.md'
  - Iniciativas Extras:
      - Materiais complementares: 'iniciativas_extras/pesquisa_de_mercado.md'
      - Identidade Visual: 'iniciativas_extras/identidade_visual.md'
      - Protótipo de Alta Fidelidade: 'iniciativas_extras/prototipo.md'
      - Testes de Usabilidade:
        - V1: 
          - Roteiro: 'iniciativas_extras/testes_de_usabilidade/v1/roteiro.md'
          - Análise: 'iniciativas_extras/testes_de_usabilidade/v1/analise.md'
        - V2: 
          - Roteiro: 'iniciativas_extras/testes_de_usabilidade/v2/roteiro.md'
      - Elicitação de requisitos:
        - Síntese dos requisitos selecionados: 'iniciativas_extras/elicitacao_de_requisitos/elicitacao_de_requisitos.md'
        - Questionário: 'iniciativas_extras/elicitacao_de_requisitos/req_questionario.md'
        - Entrevistas: 'iniciativas_extras/elicitacao_de_requisitos/req_entrevista.md'
        - Storytelling: 'iniciativas_extras/elicitacao_de_requisitos/req_storytelling.md'
        - Benchmarking: 'iniciativas_extras/elicitacao_de_requisitos/req_benchmark.md'
        - Brainstorming: 'iniciativas_extras/elicitacao_de_requisitos/req_brainstorm.md'
        - Protótipo: 'iniciativas_extras/elicitacao_de_requisitos/req_prototipo.md'
      - Kanban:
        - 5W2H Kanban: 'iniciativas_extras/kanban/5w2h.md'
        - Empresas que usam Kaban: 'iniciativas_extras/kanban/estudo_de_casos.md'
        - Comparativo entre ferramentas: 'iniciativas_extras/kanban/comparativo.md'
        - Melhorias: 'iniciativas_extras/kanban/melhorias.md'
        - Apresentação: 'iniciativas_extras/kanban/apresentacao.md'
      - Modelo de dados: 'iniciativas_extras/modelo_dados.md'
      - Backlog: 'iniciativas_extras/backlog.md'
      - Padrões: 
        - Proxy: 'iniciativas_extras/padroes/proxy.md'
        - Facade: 'iniciativas_extras/padroes/facade.md'
  - Gerência:
    - Sprint 0: 'gerencia/sprint0.md'
    - Sprint 1: 'gerencia/sprint1.md'
    - Sprint 2: 'gerencia/sprint2.md'
    - Sprint 3: 'gerencia/sprint3.md'
    - Sprint 4: 'gerencia/sprint4.md'
