 

site_name: QR Comer
site_description: Repositório da disciplina de QR Comer
repo_url: https://github.com/fga-desenho-2019-2/Wiki
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/fga-desenho-2019-2/Wiki/">QR Comer</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: favicon.ico
  favicon: favicon.ico
  palette:
    primary: 'white'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/fga-desenho-2019-2/Wiki'

plugins:
  - search

extra_css:
  - css/landing-page.css
  - css/extra.css
  
lang:
  - 'pt'

pages:
  - Home: 'index.html'
  - Dinâmica e Seminário I:
      - Termo de abertura de projeto: 'seminario1/tap.md'
      - Design Sprint: 'seminario1/design_sprint.md'
  - Iniciativas Extras:
      - Materiais complementares: 'iniciativas_extras/pesquisa_de_mercado.md'
      - Identidade Visual: 'iniciativas_extras/identidade_visual.md'
      - Kanban: 
        - 5W2H Kanban: 'iniciativas_extras/kanban/5w2h.md'
        - Empresas que usam Kaban: 'iniciativas_extras/kanban/estudo_de_casos.md'
        - Comparativo entre ferramentas: 'iniciativas_extras/kanban/comparativo.md'
        - Apresentação: 'iniciativas_extras/kanban/apresentacao.md'
